apiVersion: godpowers/v1
kind: Workflow
metadata:
  name: oss-release
  version: 1.0.0
  description: Open source library release plan. Extension workflow.

on: [/god-oss-release]

jobs:
  oss-release-plan:
    tier: 3
    uses: god-oss-release-strategist@^1.0.0
